os:
  - linux
  - osx

rvm:
  - 1.9.3
  - rbx-3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.5
  - 2.4.0
  - ruby-head

cache: bundler

before_install:
  - "echo 'gem: --no-document' > ~/.gemrc"
  - gem update --system
  - gem install bundler  # Necessary to fix 1.9.3

script: (cd childprocesscore && bundle exec rake) && (cd childprocess && bundle exec rake)

env:
  global:
  matrix:
    - CHILDPROCESS_POSIX_SPAWN=true CHILDPROCESS_UNSET=should-be-unset
    - CHILDPROCESS_POSIX_SPAWN=false CHILDPROCESS_UNSET=should-be-unset

matrix:
  include:
    - rvm: jruby-9.1.9.0
      sudo: true
      env: CHILDPROCESS_POSIX_SPAWN=true CHILDPROCESS_UNSET=should-be-unset
    - rvm: jruby-9.1.9.0
      sudo: true
      env: CHILDPROCESS_POSIX_SPAWN=false CHILDPROCESS_UNSET=should-be-unset
    - rvm: jruby-9.1.9.0
      sudo: true
      env: CHILDPROCESS_POSIX_SPAWN=true CHILDPROCESS_UNSET=should-be-unset
      os: osx
    - rvm: jruby-9.1.9.0
      sudo: true
      env: CHILDPROCESS_POSIX_SPAWN=false CHILDPROCESS_UNSET=should-be-unset
      os: osx
  allow_failures:
    - rvm: rbx-3
    - rvm: jruby-9.1.9.0
    - rvm: ruby-head
    - env: "CHILDPROCESS_POSIX_SPAWN=true"
